#%RAML 1.0
title: M.I.K.E API
version: 1
baseUri: https://mike.igrupobbva.com/mike-consumer-api/{version}/
mediaType: application/json
types:
  - Log: !include resourceTypes/logType.raml
  - MSG_IN: !include resourceTypes/msg_inType.raml
  - MSG_OUT: !include resourceTypes/msg_outType.raml
  - Health: !include resourceTypes/healthType.raml
  - Location: !include resourceTypes/locationType.raml
  - BranchAddress: !include resourceTypes/branchAddressType.raml
  - Branch: !include resourceTypes/branchType.raml
  - GeoLocation: !include resourceTypes/geoLocationType.raml
  - CMS: !include resourceTypes/cmsType.raml
  - InboundCall: !include resourceTypes/inboundCallType.raml
  - InboundCallMinus: !include resourceTypes/inboundCallMinusType.raml
  - OutboundCall: !include resourceTypes/outboundCallType.raml

resourceTypes:
  - Collection: !include resourceTypes/collectionResourceType.raml
  - Item: !include resourceTypes/itemResourceType.raml

traits:
  - FilterableByHost: !include traits/filterableByHost.raml
  - FilterableByUUAA: !include traits/filterableByUUAA.raml
  - FilterableByCookie: !include traits/filterableByCookie.raml
  - FilterableByWebContainer: !include traits/filterableByWebContainer.raml
  - FilterableByDate: !include traits/filterableByDate.raml
  - FilterableByDateTime: !include traits/filterableByDateTime.raml

/insert:
    type: { Item: {item : Log} }

/getByHost:
    type: { Collection: {item : Log} }
    get:
      is: FilterableByHost
      queryParameters:
        Host: string

/getByUUAA:
    type: { Collection: {item : Log} }
    get:
      is: FilterableByUUAA
      queryParameters:
        UUAA: string

/getByCookie:
    type: { Collection: {item : Log} }
    get:
      is: FilterableByCookie
      queryParameters:
        Cookie: string

/getByWebContainer:
    type: { Collection: {item : Log} }
    get:
      is: FilterableByWebContainer
      queryParameters:
        WebContainer: string

/getByDate:
    type: { Collection: {item : Log} }
    get:
      is: [ FilterableByDateTime , FilterableByDate ]
      queryParameters:
        Date: string
        max_timestamp: number
        min_timestamp: number
