description: ""
properties:
  branch_id: string
  branch_code: string
  operative_branch: string
  bank: string
  operative_bank: string
  branch_address: BranchAddress
  region: string
  head_branch: string
example:
  branch_id: "ES01820437"
  branch_code: "0437"
  operative_branch: "0883"
  bank: "0182"
  operative_bank: "0001"
  branch_address:
    province: 41
    post_code: 28011
    country: "SPAIN"
  region: "territorial"
  head_branch: "CBC"
