description: ""
properties:
  timestamp: number
  response_time: number
  http_status_code: number
  response_status: string
  response_code: string
example:
  timestamp: 1444389041012
  response_time: 25001
  http_status_code: 200
  response_status: "OK"
  response_code: "44725, 66884, etc (o mejor 08, 06, 12, etc.???)"
