description: ""
properties:
  user_id: string
  call_id: string
  hostname: string
  instance_name: string
  health: Health
example:
  user_id: " "
  call_id: " "
  hostname: " "
  instance_name: " "
  health:
    timestamp: 1444389041012
    response_time: 25001
    http_status_code: 200
    response_status: "OK"
    response_code: "44725, 66884, etc (o mejor 08, 06, 12, etc.???)"
