description: ""
properties:
  geolocation: GeoLocation
  branch: Branch
example:
  geolocation:
    lat: "37.3591307"
    lon: "-6.034502"
  branch:
    branch_id: "ES01820437"
    branch_code: "0437"
    operative_branch: "0883"
    bank: "0182"
    operative_bank: "0001"
    branch_address:
      province: 41
      post_code: 28011
      country: "SPAIN"
    region: "territorial"
    head_branch: "CBC"
