description: ""
properties:
  srv_href: string
  srv_type: string
  uuaa: string
  inbound_call: InboundCallMinus
example:
  srv_href: "http://ei-arqaso.igrupobbva:7050/customers/V01/123/"
  srv_type: "MSRV (Multichannel Service), NFLW (Nacar Flow), APXTX (APX transaction), MFTX (Host transaction), ROU (Routine)"
  uuaa: "ENAX, KJIM, QZQP, ATRP..."
  inbound_call:
    user_id: " "
    call_id: " "
    hostname: " "
    instance_name: " "
    health:
      timestamp: 1444389041012
      response_time: 25001
      http_status_code: 200
      response_status: "OK"
      response_code: "44725, 66884, etc (o mejor 08, 06, 12, etc.???)"
