#%RAML 0.8
title: MikeAPI
version: v1
#baseUri: http://{domain}/{apiversion}/mike
baseUri: http://mike.igrupobbva.com/mike/v1
mediaType: application/json
documentation:
  - title: Overview
    content: |
      M.I.K.E - monitoring IT Key Engine API
      This API serves endpoints to write and query over logs with different systems
      and different schemas.
      - Structured Logs: Logs which are composed following the canonical model.
      - Non-structured Logs: Logs without model, that needs to be proccessed to turn on an useful log.

schemas:
  - ResponseStructuredLog: !include schemas/responseStructuredSchema.json
  - ResponseUnstructuredLog: !include schemas/responseUnstructuredSchema.json
  - Response201: !include schemas/response201.json
  - Response500: !include schemas/response500.json
  - Response404: !include schemas/response404.json

traits:
  - eventTypeSelector:
      queryParameters:
        filters:
          description: "The filters to use in the query."
          required: false
          minLength: 3
          type: string
          example: "filters=field1:value1,field2:value2,etc..."
        fields:
            description: "The fields to expose in the results."
            required: false
            minLength: 3
            type: string
            example: "fields=field1,field2,field3,etc .."
        orderBy:
            description: "The sorting options to return the results ordered by a field or dimension."
            required: false
            minLength: 3
            type: string
            example: "orderBy=field1:asc|desc,field2:asc|desc,field3:asc|desc,etc .."
        dateFrom:
          description: "The starter date in timestamp format to filter the results in the query."
          required: true
          minLength: 13
          type: string
          example: "dateFrom=1444389041012"
        dateTo:
          description: "The top date in timestamp format to filter the results in the query."
          required: false
          minLength: 13
          type: string
          example: "dateTo=1444389041012"

/log/structured:
  displayName: log/structured
  description: |
   Requests for querying over the global health monitorization.
   It returns or write a specific kind of trace, identified by the name of the event type on the URI, it must be 'shortevent' o 'longevent'.
  get:
      description: Get all logs.
      is: [eventTypeSelector]
      responses:
          200:
              description: !include documentation/response_200.txt
              body:
                  application/json:
                      schema: ResponseStructuredLog
                      example: !include examples/responseStructuredLog200Example.json
          500:
              description: !include documentation/response_500.txt
              body:
                  application/json:
                      schema: Response500
                      example: !include examples/response500Example.json
          404:
              description: !include documentation/response_404.txt
              body:
                  application/json:
                      schema: Response404
                      example: !include examples/response404Example.json
  post:
    description: Put a new trace on the system
    body:
        application/json:
                          schema: ResponseStructuredLog
                          example: !include examples/response200Example.json
    responses:
          201:
              description: !include documentation/response_201.txt
              body:
                  application/json:
                      schema: Response201
                      example: !include examples/response201Example.json
          500:
              description: !include documentation/response_500.txt
              body:
                  application/json:
                      schema: Response500
                      example: !include examples/response500Example.json
          404:
              description: !include documentation/response_404.txt
              body:
                  application/json:
                      schema: Response404
                      example: !include examples/response404Example.json

/log/unstructured:
  displayName: log/unstructured
  description: |
   Requests for querying over the global monitorization.
   It returns or write a specific kind of trace, identified by the name of the event type on the URI.
  get:
      description: Get all logs.
      is: [eventTypeSelector]
      responses:
          200:
              description: !include documentation/response_200.txt
              body:
                  application/json:
                      schema: ResponseUnstructuredLog
                      example: !include examples/responseUnstructuredLog200Example.json
          500:
              description: !include documentation/response_500.txt
              body:
                  application/json:
                      schema: Response500
                      example: !include examples/response500Example.json
          404:
              description: !include documentation/response_404.txt
              body:
                  application/json:
                      schema: Response404
                      example: !include examples/response404Example.json
  post:
    description: Put a new trace on the system
    body:
        application/json:
                          schema: ResponseUnstructuredLog
                          example: !include examples/responseUnstructuredLog200Example.json
    responses:
          201:
              description: !include documentation/response_201.txt
              body:
                  application/json:
                      schema: Response201
                      example: !include examples/response201Example.json
          500:
              description: !include documentation/response_500.txt
              body:
                  application/json:
                      schema: Response500
                      example: !include examples/response500Example.json
          404:
              description: !include documentation/response_404.txt
              body:
                  application/json:
                      schema: Response404
                      example: !include examples/response404Example.json
